version: '3.9'

# containers
services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5438:5342
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  api:
    container_name: api
    build: ./api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
  ui:
    container_name: ui
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/tapRides
    environment: 
      NODE_ENV: ${NODE_ENV}