# Generated by Django 4.0.4 on 2022-06-18 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('event_link', models.CharField(help_text='link to event in tapestry website', max_length=100)),
                ('street_address', models.CharField(default='1521 S Hill St.', max_length=50)),
                ('city', models.CharField(default='Los Angeles', max_length=30)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('zip_code', models.IntegerField(default=90015)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('is_driver', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='JR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False)),
                ('accomodations', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(help_text='user or group who is hosting this event', on_delete=django.db.models.deletion.CASCADE, to='rides.user', verbose_name='user in charge'),
        ),
    ]
